js:

  dmWidgetNivoGalleryPlugin:
    
    view:      view
    form:      form
    nivo:      nivo-slider/jquery.nivo.slider

css:

  dmWidgetNivoGalleryPlugin:
    
    view:           view
    form:           form
    theme_default:  themes/default
    theme_bar:      themes/bar
    theme_dark:     themes/dark
    theme_light:    themes/light